version: "3.8"
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - PGUSER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=buffalobot
            - POSTGRES_INITDB_SCRIPT=/app/db/init.sql
        volumes:
            - type: volume
              source: database
              target: /var/lib/postgresql/data
            - type: bind
              source: ./db/init.sql
              target: /docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d buffalobot -c 'SELECT 1;'"]
            interval: 10s
            retries: 5
        restart: unless-stopped

    bot:
        image: ${IMAGE_NAME}:${TAG}
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DISCORD_TOKEN_KEY=${DISCORD_TOKEN_KEY}
        volumes:
            - type: volume
              source: logs
              target: /app/logs
        depends_on:
            db:
                condition: service_healthy
        restart: always

volumes:
  database:
  logs:
