version: "3.8"
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - database:/var/lib/postgresql/data
        restart: unless-stopped

    bot:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - MAX_RETRIES=5

volumes:
  database: