version: "3.8"
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_INITDB_SCRIPT=/app/init.sql
        volumes:
            - database:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
            interval: 30s
            timeout: 60s
            retries: 5
            start_period: 80s
        restart: unless-stopped

    bot:
        image: ${IMAGE_NAME}:${TAG}
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DISCORD_TOKEN_KEY=${DISCORD_TOKEN_KEY}
        depends_on:
            db:
                condition: service_healthy
        restart: always

volumes:
  database:
